/**
 * Store Memory tool — lets the agent explicitly persist facts to long-term memory.
 *
 * Use cases:
 * - "Remember that this client prefers installment payments"
 * - "Note that the customer is allergic to shellfish"
 * - "Record that vehicle inquiry was for a pickup truck, black"
 *
 * The embedding is auto-generated by the memory store from the content.
 * Risk level is low — storing memories is always reversible.
 */
import { z } from 'zod';
import type { ExecutionContext } from '@/core/types.js';
import type { Result } from '@/core/result.js';
import { ok, err } from '@/core/result.js';
import { ToolExecutionError } from '@/core/errors.js';
import type { NexusError } from '@/core/errors.js';
import type { ExecutableTool, ToolResult } from '@/tools/types.js';
import type { LongTermMemoryStore } from '@/memory/memory-manager.js';
import { createLogger } from '@/observability/logger.js';

const logger = createLogger({ name: 'store-memory' });

// ─── Options ───────────────────────────────────────────────────

export interface StoreMemoryToolOptions {
  /** The long-term memory store to persist to. */
  store: LongTermMemoryStore;
}

// ─── Schemas ───────────────────────────────────────────────────

const inputSchema = z.object({
  content: z
    .string()
    .min(1)
    .max(2000)
    .describe('The fact, preference, or decision to remember. Be concise and specific.'),
  category: z
    .enum(['fact', 'decision', 'preference', 'task_context', 'learning'])
    .describe(
      'Memory category: "fact" for objective facts, "preference" for client preferences, ' +
      '"decision" for choices made, "task_context" for task details, "learning" for lessons.',
    ),
  importance: z
    .number()
    .min(0)
    .max(1)
    .default(0.7)
    .describe('Importance score from 0.0 (trivial) to 1.0 (critical). Default: 0.7.'),
  sessionScoped: z
    .boolean()
    .default(false)
    .describe(
      'If true, memory is scoped to the current session only. ' +
      'If false (default), it persists across all sessions for this project.',
    ),
  scope: z
    .enum(['agent', 'project'])
    .optional()
    .default('agent')
    .describe(
      'Memory scope. "agent" (default) stores the memory only for this agent. ' +
      '"project" stores it as shared knowledge visible to every agent in the project.',
    ),
});

const outputSchema = z.object({
  stored: z.boolean(),
  memoryId: z.string().optional(),
  category: z.string(),
  importance: z.number(),
  sessionScoped: z.boolean(),
  scope: z.enum(['agent', 'project']),
});

// ─── Tool Factory ──────────────────────────────────────────────

/**
 * Create a store-memory tool for persisting facts to long-term semantic memory.
 * The agent calls this when it learns something worth remembering about the client.
 */
export function createStoreMemoryTool(options: StoreMemoryToolOptions): ExecutableTool {
  const { store } = options;

  return {
    id: 'store-memory',
    name: 'Store Memory',
    description:
      'Persist a fact, preference, or decision to long-term memory so it can be recalled in future conversations. ' +
      'Use for important client preferences ("prefers installment payments"), key facts ("VIP customer"), ' +
      'decisions made ("quoted $5,000 for truck"), or follow-up reminders. ' +
      'The memory will be automatically retrieved in relevant future conversations.',
    category: 'memory',
    inputSchema,
    outputSchema,
    riskLevel: 'low',
    requiresApproval: false,
    sideEffects: true,
    supportsDryRun: true,

    async execute(
      input: unknown,
      context: ExecutionContext,
    ): Promise<Result<ToolResult, NexusError>> {
      const startTime = Date.now();
      const parsed = inputSchema.parse(input);

      try {
        const stored = await store.store({
          projectId: context.projectId,
          agentId: parsed.scope === 'agent' ? context.agentId as import('@/agents/types.js').AgentId : undefined,
          sessionId: parsed.sessionScoped ? context.sessionId : undefined,
          scope: parsed.scope,
          category: parsed.category,
          content: parsed.content,
          embedding: [], // auto-generated by prisma-memory-store from content
          importance: parsed.importance,
        });

        logger.info('Stored memory via store-memory tool', {
          component: 'store-memory',
          projectId: context.projectId,
          memoryId: stored.id,
          category: stored.category,
          importance: stored.importance,
        });

        return ok({
          success: true,
          output: {
            stored: true,
            memoryId: stored.id,
            category: stored.category as string,
            importance: stored.importance,
            sessionScoped: parsed.sessionScoped,
            scope: parsed.scope,
          },
          durationMs: Date.now() - startTime,
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        logger.error('Failed to store memory', {
          component: 'store-memory',
          projectId: context.projectId,
          error: message,
        });
        return err(new ToolExecutionError('store-memory', message));
      }
    },

    dryRun(
      input: unknown,
      context: ExecutionContext,
    ): Promise<Result<ToolResult, NexusError>> {
      void context;
      const parsed = inputSchema.parse(input);
      return Promise.resolve(ok({
        success: true,
        output: {
          stored: false,
          category: parsed.category,
          importance: parsed.importance,
          sessionScoped: parsed.sessionScoped,
          scope: parsed.scope,
          dryRun: true,
          previewContent: parsed.content.substring(0, 100),
        },
        durationMs: 0,
      }));
    },
  };
}
